### ISSUE TITLE
Selecting process by typing in the name doesn't work

### ISSUE THREAD

**Issue by GH-Rake** [multikill/GH_Injector_MSVC_2019_QT_5_15_0#2]
If you select the process using the process picker, you can click the first radio button to have the injector pick the process by name and it will work.

But if you reset settings and just start the injector and type in the name into the first text box, it will say "invalid process name".

**Comment by multikill** [comment]
When entering text Process by name must be concluded with an Enter key.
When the button is pressed, the item is added to the drop-down list and then marked as Active.
The injection looks at the active element and not at the text. 

The problem lies in the function "void GuiMain::cmb_proc_name_change()". 
I can fix this in the next few days

**Comment by multikill** [comment]
Should be solved. Feel free to test it :)
